language: python

python:
 - "3.6"

before_install:
 - sudo apt-get install -y asciidoc

install:
  make
script: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: HhuYZTFJHubh91YLwgc6Mg
  on:
    branch: master
  
addons:
  apt:
    update: true
